name: HexChat
version: @version@
main: com.jih10157.hexchat.HexChat
api-version: 1.16
authors: [Lesser]

permissions:
  hexchat.*:
    default: op
    children:
      hexchat.chat.*: true
      hexchat.chat.hex: true
      hexchat.chat.rgb: true
  hexchat.chat.*:
    default: op
    children:
      hexchat.chat.hex: true
      hexchat.chat.rgb: true
  hexchat.chat.hex:
    default: op
  hexchat.chat.rgb:
    default: op
  hexchat.sign.*:
    default: op
    children:
      hexchat.sign.hex: true
      hexchat.sign.rgb: true
  hexchat.sign.hex:
    default: op
  hexchat.sign.rgb:
    default: op